yshavit/mdq

examples/hello.md, src/fmt_md.rs, src/main.rs, src/tree.rs
- write link references, with options of whether to write the link definitions at the bottom of the doc or at the end of the section in which they're first referenced
- some groundwork for footnotes
- tests are TBD and will come soon, comprehensively for `fmd_md`
=> write link references

src/fmt_json.rs, src/fmt_md.rs, src/select.rs, src/tree.rs
This gives them more consistency.
I did this using RustRover's extraction, which doesn't do perfect formatting -- it keeps extra spaces. I left them in, for no reason other than not wanting to go through and change them all manually. `cargo fmt` doesn't care, apparently.
=> extract MdqNode states to separate structs

.github/workflows/rust.yml, src/tree.rs
As a test of it, mark a passing test as ignored.
=> add check that ignored tests all fail

src/fmt_md.rs, src/main.rs, src/output.rs, src/str_utils.rs
For now, this only supports writing &str. Later, I may add a single-char variant, and pipe that down through the various Output methods.
This resolves #27.
=> add SimpleWrite trait

src/fmt_md.rs, src/main.rs, src/output.rs, src/str_utils.rs, src/tree.rs, src/tree_test_utils.rs, src/utils_for_test.rs
- Add a more generic version of the variants checker I wrote for the Node -> MdqNode conversions
- Add unit tests for all the MdqNode -> markdown renderings
- Various fixes to the prod code that shook out from those tests
=> markdown rendering tests and fixes

src/fmt_md.rs, src/tree.rs, src/utils_for_test.rs
`NodesChecker` was specific to `mdast::Node`. PR #30 added `VariantsChecker` as a more general form of the same thing; this change completes it by replacing `NodesChecker` with `VariantsChecker.
=> unify VariantsChecker and NodesChecker

src/matcher.rs, src/parse_common.rs, src/select.rs
(as opposed to `//`, which looks too confusing with regexes.)
Also move it to parse_common.
=> set the parse separator to `|`

src/fmt_md.rs, src/fmt_str.rs, src/main.rs, src/select.rs, src/tree.rs
- rename `Header` -> `Section`, to better reflect that it's a whole section (and not just the `# header text` line)
- make `MdqNode::read` return a `Vec<MdqNode>`, instead of just one. This is in anticipation of a larger reorg that formalizes blocks, leaf blocks, inlines, etc.
The impetus for this came from trying to improve the Selector logic. I realized I need a better version of MdqNode: one that is both tighter constrained for ease of rendering (as I already have with the various things that take a `Vec<Inline>`, but can also cut across the hierarchy so that I can do things like selecting individual spans (like list elements, links, etc).
=> MdqNode reorg: part 01

src/fmt_md.rs, src/fmt_str.rs, src/select.rs, src/tree.rs
Selectors will work on streams of md elements, which they'll flatmap into other streams of md elements. That means we're going to be working with iterators of elements (or for now, Vecs of them), meaning that we don't really need a special element that's just "a stream of elements".
In other words, we don't actually want to think of a doc as a single element with a list of elements -- we want to think of it as the stream of those elements.
=> get rid of `MdqNode::Root`

src/fmt_md.rs, src/output.rs, src/str_utils.rs, src/tree.rs
I'm going to go in the opposite direction of what I was thinking before: rather than pulling things out of `MdqNode`, I'm going to pull things _into_ it as needed. This is actually effectively the same my original plan, just with less hierarchy and (importantly!) less "huge diffs that don't actually improve anything".
Long live `MdqNode`!
=> add `MdqNode::ListItem`

src/fmt_str.rs, src/matcher.rs, src/select.rs
I've played around with it for manual testing and it seems to work, but no automated testing yet. Still, this is a big milestone!
For now, there's minimal (basically no) abstraction to unify list selectors with section selectors. I'll probably do that next, and then add tests, and then add more selectors.
=> add list selector

src/matcher.rs, src/parsing_iter.rs, src/select/list_item.rs, src/select/section.rs, src/select/selector.rs, src/select/util.rs
Chars holds onto the underlying &str, meaning it always comes from a &str eventually. The callers don't care what kind of iterator it is, so why have them worry about it? Just use the concrete type, fetch it directly from the &str (as opposed to having it be passed in), and be done with it.
=> simplify the ParsingIterator

src/fmt_md.rs, src/tree.rs
=> rename `Link` -> `LinkDefinition`

src/matcher.rs, src/select/section.rs
Despite the comment, I don't want to remove the `&str` version: it'll be useful when I want to write a matcher against URLs, for links and images (and also for alt text for images). But, anywhere that I'm using it to check for an inline, I should use `matches_inlines` instead.
=> remove a TODO

src/fmt_md.rs, src/fmt_str.rs, src/matcher.rs, src/select/selector.rs, src/tree.rs, src/tree_ref.rs, src/tree_test_utils.rs
- MdqNode is either Block or Inline
- Blocks are either Leafs Blocks or Containers
- sort the various node types into those leafs and containers
In service of #53.
=> split MdqNode up into more precise enums

src/fmt_md.rs, src/select/selector.rs, src/tree_ref.rs
This lets me semi-formally differentiate between elements that are selectable, and those that cannot be selected but can still be displayed.
In service of #53
=> move various MdqNodeRefs into NonSelectable

src/fmt_md.rs, src/fmt_str.rs, src/main.rs, src/matcher.rs, src/select/interface.rs, src/select/list_item.rs, src/select/selector.rs, src/tree.rs, src/tree_ref.rs, src/tree_test_utils.rs
- `MdNode` -> `MdElem`, with associated changes to the macros
- `MdqNodeRef` -> `MdElemRef`
This is during #53, but isn't really needed for that ticket. I just don't really like the "node" aspect, because it doesn't work as nicely in my head when we're dealing with a stream of them. In other words: yes it's a tree, but a lot of times the code is thinking less of its tree structure and more of it as a "thing that can be streamed".
=> various renames

src/fmt_md.rs, src/fmt_str.rs, src/select/selector.rs, src/tree.rs, src/tree_ref.rs, src/tree_test_utils.rs
- extract the inlined struct variants into actual structs
- make `Inline` be non-selectable
With this change, everything is now officially nice and tidy. Everything that's selectable is a top-level variant in `MdElemRef`, and everything that's not selectable is within the `NonSelectable` variant.
This (finally!) resolves #53
=> make Inline variants into structs

src/fmt_md.rs, src/select/api.rs, src/tree_ref.rs
I don't actually need them separated into selectable or not, and doing so is actually pretty ugly, because it means `fmt_md` is beholden to select's whims.
=> simplify the `MdElemRef` variants

examples/hello.md, src/select/api.rs
`# foo | #bar` was broken due to my previous change, in which the separator was no longer consumed by the bareword parser. So, fix that.
Also some minor cleanup.
=> selector parsing fixes

src/fmt_md.rs, src/select/api.rs, src/select/mod.rs, src/select/sel_image.rs, src/select/sel_link.rs, src/tree_ref.rs
The good news: image selector was pretty easy to add!
The bad news: look at all that boilerplate! :-( Other than a bit of refactoring in `sel_link.rs`, all this boilerplate really is the minimum I need in order to add a new matcher.
Issue #62 can't get addressed soon enough!
=> add image selector

Cargo.toml, src/select/api.rs, src/select/sel_list_item.rs, src/tree_ref.rs
Create a somewhat ugly macro that:
- creates the `MdqRefSelector` and its variants (one for each selector type)
- creates the `fn try_select_node`, which is the
`match ... (selector, node) -> selector.try_select(node)` dispatch
- creates the `fn parse_selector`, which dispatches to the various
`read(ParsingIterator)` functions
This actually results in more code (whoops!), but it means it's closer to foolproof to register a selector. You just add it to the `selectors!` list, and it handles parsing and dispatch for you.
I'm going to go ahead and say this resolves #62. It's far from perfect, but it's also plenty good enough for now. Maybe even over-engineered.
=> macro-ify selector registration

src/fmt_md.rs, src/fmt_str.rs, src/parsing_iter.rs
=> add tests and finish some TODOs

src/fmt_md.rs, src/main.rs, src/select/api.rs, src/select/base.rs, src/select/sel_image.rs, src/select/sel_link.rs, src/select/sel_list_item.rs, src/select/sel_section.rs, src/tree_ref.rs
This lets us encapsulate a `Vec<MdElem>` that represents a single area of
the doc, as opposed to a stream of disparate areas.
Note that we don't need a new `MdElem` variant, just a new `MdElemRef` variant. This is consistent with the code's existing pattern that `MdElem` is just the structure, and `MdElemRef` is various slices into that structure.
This also lets us simplify the `SelectResult`, since each selector now
returns exactly one element (previously, there was a `Multi` case for
`SectionSelector`, but now that's just a single Doc).
This resolves #79.
=> add a new MdElemRef::Doc

src/matcher.rs
- make them case-insensitive; this resolves #67 
- make `$` always an ending delimiter that gets consumed; this is in preparation for #56 
- add tests
=> bareword improvements

src/fmt_md.rs, src/fmt_md_inlines.rs, src/link_transform.rs, src/main.rs, src/utils_for_test.rs
Move the handling of inlines from `fmt_md.rs` to a separate struct.
This makes it easier to do json output (#74), since I want to render inlines via just the markdown text (not a JSON breakdown of the various spans).
Resolves #87. That was originally written as a performance improvement, but I'm doing it now for the JSON (not performance).
=> factor out inline writes

src/fmt_md.rs, src/fmt_str.rs, src/matcher.rs, src/tree.rs, src/tree_ref.rs, src/tree_test_utils.rs
Inline containers and leaf blocks.
The more precise hierarchy was a nice idea, but it just adds a lot of extra boilerplate for no real benefit.
I thought this would be helpful for #74, but I don't think it actually will be. Still, I think it's an improvement, so I'm going to keep it.
A possible next step would be to create a new struct in `tree.rs`:
pub struct Doc {
pub body: Vec<MdElem>,
}
But from trying it, it basically creates a lot more noise in the tests, and doesn't actually buy much in prod code -- so it's not worth it.
=> flatten the MdElems tree

Cargo.lock, Cargo.toml, examples/hello.md, src/fmt_md.rs, src/fmt_md_inlines.rs, src/main.rs, src/tree_ref_serde.rs
Provide `--json` output option.
This introduces now a _third_ version of the md-nodes enum, but I think it's probably  acceptable. There may be a consolidation opportunity in the future (especially with `MdElemRef`, which is already denormalized w.r.t. `MdElem`), but this is okay for now.
Resolves #74.
=> json output

examples/hello.md, src/main.rs
Allow something like:
```
cat example.md | mdq '- foo'
```
We do this by creating a hidden flag named ` ` (just a space), so that `- foo` is really the `-{space}` flag followed by an argument `foo`. We then use that to recreate the `- foo` selector string.
clap arg groups let us validate that the user doesn't specify both this list-starting selector and a normal selector:
```
$ mdq '# hello' ✅
$ mdq '- world' ✅
$ mdq '# hello' '- world' ❌
error: the argument '[selectors]' cannot be used with '-  <selectors starting with list>'
```
The error message isn't perfect, but this is good enough.
Resolves #102
=> let selector strings start with list selectors

src/main.rs
I did some very rough benchmarking on a file that's just 1000x of `examples/hello.md`, and this doesn't seem to have any effect.
But hey, why not.
resolves #95
=> lock stdout

src/matcher.rs, src/select/api.rs
Add quoted string matchers:
- can start with either a single or double quote
- escape sequences for quotes (single or double, regardless of the quote char used to start the string), tabs, newlines, and unicode escape
- case sensitive
This resolves #77. See discussion at #56.
=> quoted strings

src/select/base.rs, src/select/sel_image.rs, src/select/sel_link.rs, src/select/sel_list_item.rs, src/select/sel_section.rs, src/tree_ref.rs
Instead of only selecting the body, it selects the title as well. This also brings in a simplification to remove `fn pick(..)`, if we provide various `Into<MdElemRef>`s.
Resolves #108.
=> section selector selects the whole section

src/fmt_md.rs, src/fmt_md_inlines.rs, src/lib.rs, src/tree_ref_serde.rs, tests/md_cases/output_format.toml
Default is `--output markdown`.
This way is more flexible in the future, if I want more output formats for whatever reason.
Also fix an unrelated bug in the JSON output, which I found when I added an integ test for it.
Resolves a TODO, in service of #11.
=> change `--json` to `--output json`

src/cli.rs, src/lib.rs, src/select/api.rs, src/tree.rs
I have two spots in the code that I wasn't able to produce cases for. I
suspect these can't happen, but just in case, I'm going to put basically
an overridable panic of sorts. By default, hitting either of these cases
will result in an error; but if you provide the hidden
`--allow-unknown-markdown` flag, we'll just ignore them.
I can't test this (if I knew how to hit these branches, I wouldn't need
it!), but I manually added a `lookups.unknown_markdown("testing")?;` in
`MdElem::read` to verify that (a) it correctly errors out without the
flag, and (b) it correctly succeeds with the flag.
As part of this, I added better handling for the Err case of `MdElem::read`.
Also, replace a TODO with a reference to #84.
This PR removes all the TODOs for #11. Once it gets merged, I'll check the last …
=> handle unknown markdown

.github/workflows/build-release.yml, README.md
Also, update the readme to include information on the binaries.
=> add addestations to release builds

README.md, build.rs, src/select/api.rs, src/select/mod.rs, src/select/sel_block_quote.rs, src/tree_ref.rs, tests/md_cases/select_block_quote.toml
- syntax:
```
> matcher
```
- add integ tests (unit tests are #84)
- found a bug in matching (#144), so I added the ability to mark integ tests as ignored
- add to readme; will add to docs once this gets merged
Intellij auto-formatted my markdown, yay. Whatever.
This resolves #143.
=> add block quote selector

src/select/sel_block_quote.rs, src/select/sel_section.rs
This lets us add modifiers to them later if we want, like `#3`? idk.
See #120
=> require whitespace after `>` and `#` selectors

README.md, src/matcher.rs, src/select/api.rs, src/select/mod.rs, src/select/sel_code_block.rs, src/tree_ref.rs
Add code block selectors:
~~~
```           # all code blocks
```rust       # code blocks for rust
``` foo       # code blocks whose contents contains "foo"
```rust foo   # combined
~~~
Resolves #142
=> code block selectors

src/matcher.rs
`` \` ``  ->  `` ` ``
Resolves #136
=> escape for backticks

src/matcher.rs
`` \` `` -> `'` (_not_ `` ` ``)
resolves #136 for real
=> oops! fix escaped backtick

.github/workflows/rust.yml, src/fmt_md.rs, src/fmt_str.rs, src/matcher.rs, src/select/api.rs, src/tree.rs, src/tree_ref.rs, src/tree_ref_serde.rs
HTML can be [block-level or inline][1], but the previous implementation only allowed inline. It treated block-level HTML as a paragraph with a single HTML inline element, which has (at least) two problems: it serializes to JSON incorrectly, and it means that a paragraph search (#140) would incorrectly include these block-level HTMLs.
This resolves #34.
This issue blocks implementation of #153.
[1]: https://github.github.com/gfm/#html-blocks
=> block-level html elements

README.md, examples/hello.md, src/fmt_md.rs, src/select/api.rs, src/select/mod.rs, src/select/sel_html.rs, src/tree_ref.rs, src/tree_ref_serde.rs, tests/md_cases/select_html.toml
Works for both inline and block html. The selector doesn't differentiate between them.
Resolves #153 (modulo tests)
=> html selector: `</>`

README.md, src/fmt_md.rs, src/lib.rs, src/matcher.rs, src/select/api.rs, src/select/match_selector.rs, src/select/mod.rs, src/select/sel_block_quote.rs, src/select/sel_code_block.rs, src/select/sel_html.rs, src/select/sel_image.rs, src/select/sel_link.rs, src/select/sel_list_item.rs, src/select/sel_paragraph.rs, src/select/sel_section.rs, src/select/sel_table.rs, src/str_utils.rs, src/tree.rs, src/tree_ref.rs, src/tree_ref_serde.rs, src/vec_utils.rs, tests/md_cases/select_block_quote.toml, tests/md_cases/select_tables.toml
At long last! Table selectors.
Syntax:
```
:-: headers matcher :-: rows matcher
```
- The `headers matcher` _must_ be specified explicitly: if you want "all columns", use `*`
- Header rows are always matched, regardless of the `rows matcher`
- If the table is jagged (not all rows have the same number of columns), it will be normalized by extending all short rows with empty columns. This is a departure from the official spec, which says that the number of columns is dictated by the header row, and all longer rows are truncated. I'm making that departure intentionally, because I think it's nicer, and the output I'll provide will always be valid markdown. I may later provide a switch to control that behavior.
This resolves #141.
=> add ability to select tables

build.rs, tests/md_cases/link_placement.toml, tests/md_cases/links_references.toml, tests/md_cases/matchers.toml, tests/md_cases/output_format.toml, tests/md_cases/select_exit_code.toml, tests/md_cases/select_html.toml, tests/md_cases/select_link.toml, tests/md_cases/select_lists.toml, tests/md_cases/select_paragraphs.toml, tests/md_cases/select_sections.toml, tests/md_cases/select_tables.toml
These are tests of chaining a selector into a selector of the same type, like `# foo | #foo`. This should always apply a second filter to the same elements; it basically ANDs them together.
I added these tests for tables initially, since there are separate Table and TableSlice variants for MdElemRef; this meant that the chaining needed to be specifically supported, and was no longer a given. But, then I figured I may as well formalize that.
Some toml test case files don't need this, so there's also a mechanism to mark the chained tests as unneeded. Otherwise, a test case file without a case named "chained" will fail (the `build.rs` will auto-generate a "chained" test that trivially fails).
=> add "chained" integ tests

Cargo.lock, Cargo.toml, src/fmt_md_inlines.rs, src/utils_for_test.rs
An inline code block starts with a string of at least one backtick, but possibly more: `` ` ``, ` `` `, etc. It then continues until that same sting again.
The actual surrounding backticks don't matter, as long as they don't appear in the contents. The following are equivalent, and both produce `a``b`:
```markdown
`a``b`
```a``b```
```
The easiest way to handle this is to count the longest stretch of backticks in the contents, and then use a string of N+1 backticks for the inline code markers. So, that's what this PR does.
I can imagine nicer formatting, like finding the first available empty spot; or maybe just special-casing ` `` `. But for now, I'm keeping things simple.
If the contents start or end with backspace, we add a single space on either side of the contents (between it and …
=> handle backticks within inline code blocks

src/fmt_md.rs, tests/md_cases/link_placement.toml
When selecting individual elements (for example, `[]()` links) rather than whole sections, the `--link-pos section` switch should put the reference definitions in the same thematic-break-delimited section of the doc:
```markdown
[first][1]
[1]: https://example.com/one
-----
[second][2]
[2]: https://example.com/two
```
Fixes #132
=> fix ref placement when selecting individual elems

Cargo.lock, Cargo.toml, src/fmt_md_inlines.rs, src/tree.rs
The fix is just to accept the upstream fix, via a dependency update. Also update / fix tests as necessary.
This resolves #171.
=> handle surrounding spaces in inline code

src/output.rs, src/str_utils.rs
They're not needed, and I just learned it's more idiomatic to leave them off.
=> rm a couple generic bounds

src/output.rs, src/str_utils.rs
They're not needed, and I just learned it's more idiomatic to leave them off.
=> rm a couple generic bounds on structs

src/tree.rs
RustRover incorrectly identifies the `else` of this `if` as unreachable when it's a macro. Inlining it fixes that.
=> inline a macro invocation

src/fmt_md_inlines.rs, src/tree.rs
Fixes #88
We could output things a bit nicer, but I'm deferring that to #183. The approach in this change is functionally correct.
=> handle brackets in link text and img alt

src/fmt_md.rs, src/utils_for_test.rs
- fix the rustdoc comments
- create a builder-like constructor fn for `MdOptions`, and move some `Default` impls to `cfg(test)` (and make them not actually be `Default`)
=> test util cleanups

src/cli.rs, src/fmt_md.rs, src/fmt_md_inlines.rs, src/footnote_transform.rs, src/lib.rs, src/link_transform.rs, src/output.rs, src/tree_ref_serde.rs, src/utils_for_test.rs, tests/md_cases/footnote_renumbering.toml
Add a footnote transformer, which just assigns sequential numbers to
footnotes starting at `1`.
A note on `drain_pending_footnotes`: in this change, we transform the
`&'md String`s into full `String`s during the drain, so that we can
easily use them as a sort key. We could have done something more clever,
like creating an enum that captures either the `&md String` or the
`usize` of the transformation, and then compares those; but that felt
like more effort than we really need, especially given that the current
implementation of `FootnoteTransformer::write` eventually String-ifies
the `usize` anyway; this just does it ahead of time. In practice, we
only expect to see a handful of footnotes, and each of them will only be
a handful of chars long (even 10,000 footnotes would only be 5-chars …
=> renumber footnotes

build.rs, tests/integ_test.rs, tests/md_cases/output_format.toml
JSON is hard to read when it's all one line, so this makes it easier to see what's actually happening.
Also drop non-alphanumeric, non-whitespace chars from the integ test names. Otherwise, they become double underlines (`foo: bar` -> `foo__bar`), which triggers style warnings.
=> improve json integ tests

src/fmt_md_inlines.rs, tests/integ_test.rs, tests/md_cases/footnotes_in_footnotes.toml
Links can't contain other links or footnotes -- but footnotes can contain either. Add tests and logic to handle it.
Resolves #98.
I found #188 (footnotes that cycle back to themselves) while writing tests for this, but that's a special case, so I'm going to handle it separately.
=> handle footnotes that contain footnotes or links

src/fmt_md.rs, src/fmt_md_inlines.rs, src/fmt_str.rs, src/lib.rs, src/link_transform.rs, src/select/api.rs, src/tree.rs, src/tree_ref.rs, src/tree_ref_serde.rs, tests/md_cases/footnotes_in_footnotes.toml
Rather than having the reference's definition (ie, body) directly into the Inline element, separate it out into a new MdContext that gets returned alongside the nodes. This forces us to add indirection when looking up footnotes, which lets us handle cycles.
Resolves #188
=> separate footnote bodies into a doc-scoped context

src/output.rs, src/str_utils.rs
Rather than implementing `write_char` in terms of `write_str`, make Output more stream-like by having `write_char` be the canonical form, and `write_str` delegate to it.
This resolves #195
=> make `Output::write_char` canonical

README.md
This reduces the amount of whitespace and makes it easier to see everything at a glance.
=> readme: change list formatting to table

.github/workflows/build-release.yml, .github/workflows/rust.yml, Cargo.lock, Cargo.toml
- add a check that `cargo build` doesn't result in a dirty git tree; this ensures that `Cargo.toml` and `Cargo.lock` are in sync
- fix the `Cargo.lock`, which will in turn fix `--version`
Resolves #222
=> fix `--version`

.github/workflows/readme-checks.yml, .github/workflows/rust.yml, README.md
=> add msrv check

.github/workflows/build-release.yml, README.md
Push to `yshavit/mdq:latest` on merge to main, with an option to also push to a stable release version (e.g. `0.3.1`).
In service of #217.
=> build a docker image on merge to main

.github/workflows/readme-checks.yml, README.md
- fix the workflow name
- fix the job name
- rm the `needs` dependency
- put in the correct version to the readme (I had previously put an intentionally incorrect one, to prove this script works; and then I forgot to remove it)
In service of (and may resolve) #221
=> fixes to readme checks

.github/workflows/readme-checks.yml
Instead of running `cargo build`, just use the docker image we now publish.
=> minor: use docker image when checking readme for rustc version

tests/md_cases/select_tables.toml
The error we get is:
```
Syntax error in select specifier:
┃ :-: /description/ :-:
┃                  ↑ expected ":"
```
see #211
=> add ignored test for bug

build.rs, src/lib.rs, tests/integ_test.rs, tests/md_cases/select_html.toml, tests/md_cases/select_paragraphs.toml
Rather than having bad queries always just `eprintln` to stderr and then return false, have the `lib.rs` runners return a Result, where the error case is that invalid query's error. Then, use that to test for the error string.
=> test stderr in integ tests

Cargo.lock, Cargo.toml, src/matcher.rs, src/query/grammar.pest, src/query/query.rs, src/query/selectors.rs, src/query/strings.rs, src/select/api.rs, tests/md_cases/bad_queries.toml, tests/md_cases/select_html.toml
Use pest's new (as of 2.8.0) `PUSH_LITERAL`. This reduces the number of rules we need in the grammar.
One complication is that the `string` rule now needs to end with `DROP`. So we could either keep the `string` as only non-empty and then add the `DROP` after each `string?`, or we could have it include empty. The latter is simpler, but means we need to then add a check for explicit `*` in the table matcher.
=> use `PUSH_LITERAL` to simplify grammar

.github/workflows/release-publish.yml, src/cli.rs, src/fmt_md.rs, src/fmt_plain.rs, src/lib.rs, src/utils_for_test.rs, tests/md_cases/output_format.toml
- In markdown output, this controls whether matched elements have thematic break ( `-----` ) between them. The default is yes, and `--no-br` turns that off.
- In plain output, this controls whether matched elements have a newline between them. The default is no, and `--br` turns it on.
This resolvse #270.
=> option to output with or without breaks

.github/workflows/system-test.yml, scripts/common.sh, scripts/system_test, src/lib.rs
These are driven by the same toml files as the in-memory integ tests, but work against a real binary, via shell. This is in preparation for #275, where I'll want to be a bit trickier with inputs.
=> add end-to-end system tests

src/fmt_md.rs
Add tests of a bunch of different element types, but not all of them (it was reaching diminishing returns). I made sure to get a mix of block-type, inline-type, and line-type items.
Resolves #288.
=> fix --no-pr in markdown mode

src/lib.rs, src/main.rs, tests/integ_test.rs
Add stdout and Error handling to OsFacade. This lets us unify the two previous implementations (`run_stdio` and `run_in_memory`).
In service of #213.
=> unify the two IO implementations

src/md_elem/tree.rs, src/query/selector_try_from.rs, src/run/run.rs, src/select/api.rs, src/select/match_selector.rs, src/select/mod.rs, src/select/sel_chain.rs, src/select/sel_list_item.rs, src/select/sel_table.rs, src/select/selector.rs
Instead of having a separate SelectorChain, create a new variant Selector::Chain.
The SelectorChain struct had a slightly different contract than Selectors: it worked on a stream of MdElem (rather than just a 1:1 mapping), and essentially flatmapped it, with the extra caveat that an empty chain on an MdDoc would not flatmap, but just return the MdDoc directly. This has now been encoded into ChainSelector::try_select.
resolves #315
=> remove SelectorChain struct

src/md_elem/tree.rs, src/md_elem/tree_ref.rs, src/output/fmt_md.rs, src/output/fmt_plain_inline.rs, src/output/tree_ref_serde.rs, src/select/sel_table.rs, src/util/str_utils.rs
In service of #307: hide `mdast::AlignKind` from the public API.
=> remove public exposing of mdast::AlignKind

src/output/fmt_plain_str.rs, src/query/matcher_try_from.rs, src/query/selector_try_from.rs, src/select/api.rs, src/select/matcher.rs, src/select/string_matcher.rs
In service of #307: hide `regex::Regex` from the public API.
=> remove public exposing of regex::Regex

src/run/run.rs
Don't actually expose much about them; basically just a Display.
This is in service of #307. That ticket says to hide pest, but actually it was already hidden. The closest we got was in exposing `run::Error::QueryParse { error: ParseError, .. }`, but `ParseError` itself was not pub.
This makes it a bit hard to work with, so this PR actually exposes it a bit _more_. The pest aspect remains hidden, but `QueryParse` is now a pub struct with private fields and a pub `impl Display`.
=> expose query string errors a bit

src/output/fmt_md.rs, src/output/fmt_md_inlines.rs, src/output/fmt_plain_inline.rs, src/output/link_transform.rs, src/output/mod.rs, src/output/output_adapter.rs, src/output/tree_ref_serde.rs, src/run/cli.rs, src/run/run.rs, src/select/api.rs, src/select/string_matcher.rs, src/util/output.rs, src/util/utils_for_test.rs
In service of #213. This basically cleans up the `output::` mod, and presents a nicer interface to it. I wanted to keep the existing code more or less in place, so a lot of this is just setting up appropriate facades, and `pub use`ing those instead of the underlying.
=> fix public API for various output-related classes

src/main.rs, src/run/cli.rs, src/run/run.rs, tests/integ_test.rs
- CliOptions still exists, but is hidden
- RunOptions is visible, and that's what people should use
- define the args via a macro, so that they're in sync
This doesn't hide clap from the dependencies, but it does hide it from the public-facing API.
In service of #307.
=> expose Cli args as RunOptions

.github/workflows/build-release.yml, .github/workflows/list-targets.yml
- define more standard target names
- for everything except macOS, use `cross` to cross-compile (resolves #283; but only for the build, because I still prefer my workflow for the actual release)
- add musl for alpine linux (#313, but won't mark it resolved until I actually publish the release)
Listing the targets is done as a separate workflow, so that I can use it the release process later on.
=> better cross-compilation

src/lib.rs, src/md_elem/mod.rs, src/md_elem/tree.rs, src/output/fmt_md.rs, src/output/fmt_md_inlines.rs, src/output/fmt_plain_inline.rs, src/output/fmt_plain_str.rs, src/output/link_transform.rs, src/output/mod.rs, src/output/output_adapter.rs, src/query/matcher_try_from.rs, src/query/selector_try_from.rs, src/run/cli.rs, src/run/mod.rs, src/run/run.rs, src/select/api.rs, src/select/matcher.rs, src/select/mod.rs, src/select/sel_table.rs, src/select/selector.rs, src/select/string_matcher.rs
Also includes a few small tweaks other than docs:
- remove the `Any` enum, and replace it with just an `explicit: bool` on `Matcher::Any`
- rename `TextVariant::Html` -> `TextVariant::InlineHtml`
- rm `PlainWriter::options(&mut self) -> &mut PlainWriterOptions`, which isn't needed
- make `inlines_to_plain_string` `pub(crate)` instead of `pub`
- rename `Table::column` -> `headers`, and `row` -> `rows`
resolves #335.
=> add user-facing docs to API

Cargo.lock, Cargo.toml, src/query/matcher_try_from.rs, src/query/selector_try_from.rs, src/select/matcher.rs, src/select/string_matcher.rs, tests/md_cases/bad_queries.toml
- change the library to use fancy-regex (this uses the old regex under the hood)
- update the error handling: fancy-regex's default error handling wasn't very nice as an inner error, so I unwrapped it for nicer display
- add a unit test to smoke test the new available functionality. I only picked one new bit of functionality (lookahead) because I'm interested in verifying that fancy-regex is being used at all, not in testing the library
This is not breaking, because the regex library that mdq uses is intentionally obscured in the public API.
resolves #121
=> change to fancy-regex

README.md, examples/hello.md, src/md_elem/tree.rs, src/output/fmt_md.rs, src/output/fmt_md_inlines.rs, src/output/fmt_plain_inline.rs, src/output/tree_ref_serde.rs, src/query/grammar.pest, src/query/pest.rs, src/query/selector_try_from.rs, src/query/traversal_composites.rs, src/run/run_main.rs, src/select/api.rs, src/select/sel_code_block.rs, src/select/sel_single_matcher.rs, src/select/selector.rs, src/select/string_matcher.rs, src/util/str_utils.rs, tests/md_cases/select_front_matter.toml
Add front matter parsing and selection. The syntax is:
```text
+++variant contents
```
```md
---
title: my title
---
```
The following will match:
```
+++
```
```
+++ my title
```
```
+++yaml
```
```
+++yaml my title
```
... but this won't:
```
+++toml
````
- rm `CodeVariant::{ Toml, Yaml }` (these really should have been front matter variants, not general code variants)
- add `MdElem::FrontMatter`, with supporting types for the contents and variants
- `ParseOptions::default()` now enables front matter
- add a new selector (this isn't actually a breaking change, since the selectors enum is non-exhaustive; but it's worth mentioning)
- `BlockHtml` no longer implements `Display`; it was the only one of its siblings that did, so this makes it more consistent with the others
Resolves #214
=> add support for front matter

src/query/match_replace_try_from.rs, src/query/mod.rs, src/query/selector_try_from.rs, src/select/match_replace.rs, src/select/mod.rs, src/select/selector.rs, src/select/string_matcher.rs
This will eventually serve as a search-replace mechanism for a search-and-replace.
In service of #277.
Breaking change:
- the various selector matchers now take MatchReplace instead of Matcher
=> add MatchReplace

src/select/string_matcher.rs
For now, just pass it through; we're not going to use it yet. That'll be subsequent PRs.
In service of #277.
=> pipe the replacement string from MatchReplace to StringMatcher

scripts/system_test, src/run/run_main.rs, tests/integ_test.rs
Instead, just use `#[cfg(test)]`.
`env::set_var` is not thread-safe.
=> don't use MDQ_PORTABLE_ERRORS env var

src/md_elem/tree_ref.rs, src/select/api.rs, src/select/match_selector.rs, src/select/sel_code_block.rs, src/select/sel_link_like.rs, src/select/sel_list_item.rs, src/select/sel_section.rs, src/select/sel_single_matcher.rs, src/select/sel_table.rs, src/select/selector.rs, src/select/string_matcher.rs, src/util/vec_utils.rs, tests/md_cases/search_replace_errors.toml
Instead of ignoring the replacement, check for it in `StringMatcher::matches` and return an Err if the replacement is `Some`. In a subsequent PR, we'll be allowing it in very limited cases (link and image URLs).
Includes lots of testing!
=> make replacement always be an error

src/md_elem/tree.rs, src/output/fmt_md.rs, src/output/fmt_md_inlines.rs, src/output/fmt_plain_inline.rs, src/output/fmt_plain_str.rs, src/output/link_transform.rs, src/output/tree_ref_serde.rs, src/select/api.rs, src/select/sel_link_like.rs
The `mdq::md_elem::elem::Link` type has changed from a struct to an enum, with variants for normal links (containing the struct's previous information) and autolinks.
This feels a bit cumbersome, but I think it correctly models the difference between normal links and autolinks. The alternatives I considered were:
- Not encoding autolink-ness at all, and instead just inferring it from the link's display text, title, and URL. This works in many cases, but would also convert intentionally-not-autolinks into autolinks. It also feels like autolinks shouldn't participate in link transformation.
- Adding a variant to the `LinkReference` enum for `Autolink` (or alternatively, adding an is-autolink flag to `LinkReference::Inline`). This would be a smaller change, but still an API-breaking one. …
=> handle autolinks in parsing and rendering

src/md_elem/tree.rs, src/output/fmt_md.rs, src/output/link_transform.rs, src/output/tree_ref_serde.rs, src/run/cli.rs, src/run/run_main.rs
Add variants and attributes to future-proof enums. My guiding principles were:
1. enums that reflect markdown should be exhaustive, since we can assume a fairly stable markdown spec
2. enums that reflect mdq-specific inputs or non-markdown outputs (specifically, errors) should be non-exhaustive, so that mdq can add new features without breaking the API
Resolves #377. See that ticket for an analysis of the enums currently in the code base.
- add `FrontMatterVariant::Json` variant
- change `FrontMatterVariant::separator()`'s signature to reflect that Json doesn't have a separator line.
- add various `#[non_exhaustive]` attributes
=> future-proof enums

src/output/link_transform.rs, src/run/cli.rs, tests/md_cases/links_references.toml
Adds a new option, which will keep references, collapsed, and shortcut links as they were (other than reordering them -- see #390), but turns inlines into numbered full references. This new option is now the default.
Also adds a bunch of comments.
Resolves #176
- Adds a new enum variant, `LinkTransform::NeverInline`. This variant is now the `LinkTransform::default()`.
- `RunOptions::default()` now uses `LinkTransform::NeverInline` as its default link formatter.
=> add a LinkTransform::NeverInline option

Cargo.toml, src/md_elem/flat_inlines.rs, src/md_elem/inline_regex_replace.rs, src/md_elem/mod.rs, src/md_elem/tree_test_utils.rs, src/query/pest.rs, src/select/string_matcher.rs, src/util/output.rs
The core of this change is flat_inlines.rs, which lets you:
1. Translate a Vec<Inline> (which is a recursive data structure) into a flat representation. This representation is (a) a plain String, and (b) a series of formatting events, specified by offset and length. For example, "bold starting at char 5 for 10 chars".
2. Replace a slice of this flattened structure with another string.
3. Unflatten the structure back into Vec<Inline>
This will be used in #376.
=> add utility for replacing strings within Inlines

Cargo.toml, src/md_elem/flat_inlines.rs, src/md_elem/tree.rs, src/output/fmt_plain_str.rs, src/select/match_replace.rs, src/select/match_selector.rs, src/select/sel_code_block.rs, src/select/sel_link_like.rs, src/select/sel_list_item.rs, src/select/sel_section.rs, src/select/sel_single_matcher.rs, src/select/sel_table.rs, src/select/string_matcher.rs, tests/md_cases/search_replace.toml
This uses the new flat_inlines (#402) to replace all of the string-matching that the selectors had previous had, with a new regex-replace functionality. Resolves #376.
=> implement regex-replace for all selectors

.github/workflows/rust.yml, help.txt
This will let us track changes to `--help`. This is in service of #300, which will require a refactoring/retooling of how we generate the CLI options.
=> check in help text, and add CI to verify it
