yshavit/mdq

examples/hello.md
src/fmt_json.rs
src/fmt_md.rs
src/select.rs
src/tree.rs

Still lots to do, but the basics are working!
A lot of the diff in `src/tree.rs` is indentation, so I'd recommend viewing with 'ignore whitespace".

first pass at links and images

---

src/fmt_json.rs
src/fmt_md.rs
src/select.rs
src/tree.rs

Also mark MDX nodes as officially TODO.

implement footnotes

---

src/fmt_md.rs
src/main.rs

I'll be adding state to the wrapper in a sec, but I want to get this diff in first, since it's mostly just indentation (plus adding some `Self::`s as needed).

add wrapper struct for fmt_md functions

---

examples/hello.md
src/fmt_md.rs

- Still need tests!
- It's printing some extra newlines after paragraphs.
I can clean those up later.

basic footnote support

---

.github/workflows/coverage.yml
README.md

add job to count pending TODOs

---

src/tree.rs

use macros instead of helpers

---

src/tree.rs

autolink tests

---

src/main.rs
src/parsing_iter.rs
src/select.rs

Start from scratch, this time with good unit testing as we go.
Slow start, but this is an incremental approach now.

redoing Selectors

---

src/main.rs
src/matcher.rs
src/parse_common.rs
src/parsing_iter.rs
src/select.rs

No functional changes, just cut-pasting code around.

move code around

---

Cargo.lock
Cargo.toml
README.md

- clean up dependencies
- update dependencies
- add links to readme shield images

cleanups to Cargo.toml, README.md

---

src/output.rs
src/select.rs
src/utils_for_test.rs

Some I did, some I don't need to note.

rm some TODOs

---

src/fmt_md.rs

When we write the link definitions, write them in alphabeical order, rather than in the order they appear in the markdown.
Eventually I could see this being configurable, but for now it's not.

order link definitions in md output

---

rustfmt.toml
src/main.rs
src/matcher.rs
src/parse_common.rs
src/parsing_iter.rs
src/select/api.rs
src/select/sel_list_item.rs
src/select/sel_section.rs

- nicer helper funcs
- make the line index be 0 (nicer for programmers)
- display a helpful error message if the selector fails to parse
- make the bareword selector dynamic, which will be useful for links/images

various parser improvements

---

src/fmt_md.rs
src/matcher.rs
src/parsing_iter.rs
src/select/api.rs
src/select/mod.rs
src/select/sel_link.rs
src/select/sel_section.rs
src/tree_ref.rs

Also fixes and improvements to matching.
The various places I had to add this definitely underscore the need for issue #62.

link selectors!

---

src/fmt_md.rs

Cleanup, renames, consolidation of code.

fmt_md: links refactoring

---

src/fmt_md.rs

This makes it a bit visually clearer what's going on.
Also, consolidate thematic breaks: regardless of whether they're "organic" in the doc, or the ones we're adding as part of this, don't ever output two in a row.
That may be controversial (maybe someone wants that?) but it'll be good for now. Eventually I'll probably make this configurable.

add thematic breaks between outputted elements

---

Cargo.lock
Cargo.toml
src/fmt_md.rs
src/main.rs

Also a --footnote-pos that by default is the same as --link-pos.
This resolves #75

use clap for CLI, and add --link-pos switch

---

.github/workflows/build-release.yml

add build-release.yml

---

.github/workflows/build-release.yml
scripts/installer.sh

macos installer for the build-release jobs

---

src/main.rs

Followup to #105: add unit tests

add CLI unit tests

---

src/matcher.rs

We previously had three variants of StringMatcher:
- Any, which can pretty trivially and cheaply compiled to a regexo
- Substring, which uses regex when case-insensitive (in barewords), and also uses regex for case-sensitive searches as a simplification (that's not necessary, but it's easier and still cheap enough)
- Regex, which obviously uses regex
Rather than have these three variants be separate, I'll just unify them. Having them as variants is premature optimization.

inline Regex into StringMatcher

---

src/matcher.rs

implement string anchors

---

src/fmt_md.rs
src/fmt_md_inlines.rs
src/lib.rs
src/link_transform.rs
src/tree_ref_serde.rs
tests/md_cases/links_references.toml
tests/md_cases/select_link.toml

`--link-canonicalization` -> `--link-format`

---

README.md

Add a readme with lots of instructions.
Outstanding:
You can see the rendered version [here].
This resolves #85
[here]: https://github.com/yshavit/mdq/blob/readme/README.md

fill out the readme

---

src/fmt_md.rs
src/link_transform.rs
src/select/api.rs
src/tree_ref_serde.rs

rm a bunch of TODOs

---

build.rs
src/lib.rs
tests/integ_test.rs
tests/md_cases/matchers.toml
tests/md_cases/select_exit_code.toml

set exit code based on matches; add `--quiet`

---

src/cli.rs
src/lib.rs
src/main.rs
tests/integ_test.rs

Just a straight move, no logic change at all.

move Cli to separate file

---

README.md
build.rs
src/parsing_iter.rs
src/select/api.rs
src/select/sel_list_item.rs
src/tree_ref.rs

Also some small fixes.
This isn't _super_ extensive, but it's good enough; the rest of the code that isn't covered is pretty straightforward.
resolves #84

add unit tests for selectors

---

README.md
src/select/api.rs
src/select/mod.rs
src/select/sel_paragraph.rs
src/tree_ref.rs
tests/md_cases/select_paragraphs.toml

add paragraph selector

---

src/select/api.rs
src/select/sel_table.rs
src/tree_ref.rs
src/tree_ref_serde.rs

This lets us get their len when we need it.

expose table rows as &Vec

---

src/matcher.rs

add unit tests of anchor + whitespace

---

tests/md_cases/paragraph_spans.toml

This resolves #25, I think. :-)
The issue said I should test different spans across lines. I'm not entirely sure what about them I wanted to test... but this tests the markdown that was in the issue.

add test of paragraphs, formatting, and spans

---

src/fmt_md.rs

If the contents of the code blocks have leading backticks, extend the surrounding backticks as appropriate.
I could do something more clever by using `~~~` instead of `` ``` ``, but it's more complicated (and produces less obvious markdown, imo).
resolves #173

handle nested code blocks

---

src/fmt_md.rs
src/output.rs

Also add a test and some documentation.
resolves #196

rename Block::Inline -> Indent

---

README.md

Stick the binary validation within a <details> tag

README.md: binary validation

---

Cargo.toml

update version to 0.3.0 to match with the release.

fix: update version to 0.3.0

---

README.md

Add three examples of possible usages to the readme.

README.md: add some examples

---

.github/workflows/build-release.yml

Followup to #223. I had forgotten to set the shell.

fix windows release

---

README.md

Mention how to use specific release tags.

readme: tweaks to docker docs

---

README.md

- add mention of mdq-playground. This resolves #218 
- tweaks to `<details>` within the binaries section

readme: playground, and install tweaks

---

src/fmt_md_inlines.rs

Resolves #183.
There may be a nicer implementation though.

links: don't escape balanced brackets in descriptions

---

.github/workflows/rust.yml
scripts/cargo_to_gh

- `cargo_to_gh` was incorrectly swallowing exceptions
- use `RUSTFLAGS` to avoid the error about multiple targets

fix build scripts

---

.github/gha_assets/release_pr_template.md
.github/workflows/release-publish.yml
release_procedure.md

Finish the workflows, and adjust the documentation accordingly.
This resolves #243.

finish the release workflows revamp

---

.github/workflows/build-release.yml
.github/workflows/prepare-new-release.yml
.github/workflows/release-assets.yml

update some github action versions

---

.github/workflows/build-release.yml
.github/workflows/release-assets.yml

This is an attempt to address #276. I'll have to draft a release before I can be sure.

chmod +x for linux and mac

---

.github/gha_assets/release_pr_template.md
.github/workflows/binary-verify.yml
.github/workflows/release-assets.yml
.github/workflows/release-publish.yml

- their versions
- that they run at all (especially Windows)
- attestations
This automates most of `release_pr_template.md`, and does so across all platforms.

add workflow to verify binaries

---

src/cli.rs
src/fmt_md.rs
src/fmt_md_inlines.rs
src/fmt_plain.rs
src/fmt_str.rs
src/link_transform.rs
src/select/api.rs
src/select/sel_table.rs
src/tree.rs
src/tree_ref.rs
src/tree_ref_serde.rs
src/tree_test_utils.rs
src/utils_for_test.rs

I don't want to export these as part of the API.
resolves #308

replace `macro_export` with `pub(crate) use`

---

.github/gha_assets/crate-doc-root-redirect.html
.github/workflows/readme-checks.yml

add job for publishing crate docs to GH pages

---

src/fmt_md_inlines.rs
src/fmt_str.rs
src/lib.rs
src/md_elem/tree.rs

Encapsulation; hide the mdast dep

reworking md parsing

---

src/md_elem/tree.rs
src/output/fmt_md.rs
src/output/fmt_md_inlines.rs
src/output/fmt_plain_inline.rs
src/output/tree_ref_serde.rs
src/select/api.rs
src/select/sel_list_item.rs
src/select/string_matcher.rs
tests/md_cases/output_format.toml

remove detached ListItem

---

src/md_elem/tree.rs
src/output/link_transform.rs
src/query/matcher_try_from.rs
src/query/selector_try_from.rs
src/run/run.rs
src/select/api.rs
src/select/matcher.rs
src/select/mod.rs
src/select/sel_section.rs
src/select/sel_single_matcher.rs
src/select/selector.rs

With this PR, I think the API is in a shape I like. Now I just need to document it and do the various workflow stuffs.
In service of #213, and I think this is the last code change for #307.

finishing touches (I hope?) on the shape of the API

---

.github/workflows/list-targets.yml

minor fixes to list-targets.yml

---

.github/workflows/binary-verify.yml
.github/workflows/list-targets.yml
.github/workflows/release-assets.yml

Use the new build artifacts from #340 for preparing and validating the release.

use new build artifacts in the release

---

.github/release.yml

Add `.github/release.yml` file as described in https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

add release.yml

---

src/query/strings.rs
src/run/cli.rs
src/run/run.rs
src/select/api.rs

- implement a `From`
- rm two other TODOs:
- the one about using `s.body` is wrong; I do actually want a Doc
- the one about moving the tests isn't actually that important
Resolves #326

address some TODOs

---

Cargo.lock
Cargo.toml
src/lib.rs
src/main.rs
src/md_elem/mod.rs
src/md_elem/tree.rs
src/output/fmt_md.rs
src/output/fmt_md_inlines.rs
src/output/fmt_plain_inline.rs
src/output/fmt_plain_str.rs
src/output/link_transform.rs
src/output/mod.rs
src/output/output_adapter.rs
src/output/tree_ref_serde.rs
src/query/error.rs
src/run/cli.rs
src/run/mod.rs
src/run/run.rs
src/select/api.rs
src/select/matcher.rs
src/select/mod.rs
src/select/sel_link_like.rs
src/select/selector.rs
tests/integ_test.rs

Note that several of these changes would be breaking if someone were using the API; but since I haven't published it yet, I'm not treating those as breaking changes for purposes of release notes.
Resolves #304
Resolves #305

code changes to prepare the public API

---

src/lib.rs

add warning about breaking changes

---

.github/workflows/release-publish.yml

This resolves #306... if it works. :-)
We'll find out when I cut the release!

publish to crates.io

---

.github/workflows/readme-checks.yml
Cargo.toml

add msrv to Cargo.toml

---

Cargo.lock
Cargo.toml
src/query/strings.rs

- `cargo update`
- rm `pretty_assertions`, which I didn't really need

Dependencies cleanup

---

.github/workflows/prepare-new-release.yml

remove actions-rs/toolchain

---

src/md_elem/concatenate.rs
src/md_elem/mod.rs
src/md_elem/tree.rs

concatenate similar text and span segments

---

README.md

readme: add link to crates/docs

---

README.md

This is the last ticket to resolve #378

add regex replace to readme

---

src/util/output.rs

- they no longer describe what's in that ticket (after a few refactorings)
- they suggest optimization, but I don't if it's needed
resolves #199 (by virtue of not doing it)

remove comments that reference #199

---

src/run/cli.rs

Move the docs to the macro invocation.

refactor crate_options_structs macro
